jest.mock('../lib/github-helper', () => ({}))

import {
  resolveTitleAndBody,
  DEFAULT_TITLE,
  DEFAULT_BODY
} from '../lib/create-pull-request'
import {Commit} from '../lib/git-command-manager'

describe('resolveTitleAndBody', () => {
  const createMockCommit = (subject: string, body: string): Commit => ({
    sha: 'abcdef1234567890abcdef1234567890abcdef12',
    tree: 'tree1234567890',
    parents: ['parent1234567890'],
    signed: false,
    subject,
    body,
    changes: [],
    unparsedChanges: []
  })

  test('single commit with subject and body defaults title and body to commit', () => {
    const commits = [
      createMockCommit(
        'Update AGP sources to the latest',
        'Auto-generated by dump-sources workflow.'
      )
    ]
    const result = resolveTitleAndBody(
      {title: '', body: '', bodyPath: ''},
      commits
    )
    expect(result.title).toEqual('Update AGP sources to the latest')
    expect(result.body).toEqual('Auto-generated by dump-sources workflow.')
  })

  test('single commit with subject only defaults title to commit and body to empty string', () => {
    const commits = [createMockCommit('Update dependencies', '')]
    const result = resolveTitleAndBody(
      {title: '', body: '', bodyPath: ''},
      commits
    )
    expect(result.title).toEqual('Update dependencies')
    expect(result.body).toEqual('')
  })

  test('multiple commits fall back to DEFAULT_TITLE and DEFAULT_BODY', () => {
    const commits = [
      createMockCommit('Commit 1', 'Body 1'),
      createMockCommit('Commit 2', 'Body 2')
    ]
    const result = resolveTitleAndBody(
      {title: '', body: '', bodyPath: ''},
      commits
    )
    expect(result.title).toEqual(DEFAULT_TITLE)
    expect(result.body).toEqual(DEFAULT_BODY)
  })

  test('zero commits fall back to DEFAULT_TITLE and DEFAULT_BODY', () => {
    const result = resolveTitleAndBody({title: '', body: '', bodyPath: ''}, [])
    expect(result.title).toEqual(DEFAULT_TITLE)
    expect(result.body).toEqual(DEFAULT_BODY)
  })

  test('explicit title and body override commit defaults', () => {
    const commits = [createMockCommit('Commit subject', 'Commit body')]
    const result = resolveTitleAndBody(
      {title: 'Custom Title', body: 'Custom Body', bodyPath: ''},
      commits
    )
    expect(result.title).toEqual('Custom Title')
    expect(result.body).toEqual('Custom Body')
  })

  test('bodyPath preserves provided body and does not overwrite with commit body', () => {
    const commits = [createMockCommit('Commit subject', 'Commit body')]
    const result = resolveTitleAndBody(
      {title: '', body: 'Body from file', bodyPath: 'path/to/body.md'},
      commits
    )
    expect(result.title).toEqual('Commit subject')
    expect(result.body).toEqual('Body from file')
  })

  test('truncates body if it exceeds 65536 characters', () => {
    const longBody = 'a'.repeat(70000)
    const commits = [createMockCommit('Large commit', longBody)]
    const result = resolveTitleAndBody(
      {title: '', body: '', bodyPath: ''},
      commits
    )
    expect(result.body.length).toEqual(65536)
  })
})
