name: Create Release
on:
  push:
    tags:
      - '**'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} \
          --title "Create Pull Request ${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
      - name: Update major tag
        run: |
          MAJOR_TAG=$(echo "${{ github.ref_name }}" | sed -E 's/^v([0-9]+)\..*$/v\1/')
          git tag -f "$MAJOR_TAG" "${{ github.ref_name }}"
          git push origin "$MAJOR_TAG" --force
