name: Create Release
on:
  push:
    tags:
      - '**'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub release
        run: |
          gh release create ${{ github.ref_name }} \
          --title "Create Pull Request ${{ github.ref_name }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
